
from telethon.tl.functions.account import (UpdateProfileRequest,
                                           UpdateUsernameRequest)
from Config import HNDLR, BOT_TOKEN, BOT_HNDLR, ALIVE_NAME, ALIVE_LOGO, BOTLOG_CHATID, HASH_CHAT, REPO_LINK, STRING, SUDO, BIO_MESSAGE, API_ID, API_HASH, HEROKU_API_KEY, UPSTREAM_REPO, UPSTREAM_REPO_BRANCH, UPSTREAM_REPO_URL, HEROKU_APP_NAME
from Config import STRING, STRING2, STRING3, STRING4, STRING5, STRING6, STRING7, STRING8, STRING9, STRING10, STRING11, STRING12, STRING13, STRING14, STRING15, STRING16, STRING17, STRING18, STRING19, STRING20, STRING21, STRING22, STRING23, STRING24, STRING25, STRING26, STRING27, STRING28, STRING29, STRING30, STRING31, STRING32, STRING33, STRING34, STRING35, STRING36, STRING37, STRING38, STRING39, STRING40, STRING41, STRING42, STRING43, STRING44, STRING45, STRING46, STRING47, STRING48, STRING49, STRING50, STRING51, STRING52, STRING53, STRING54, STRING55, STRING56, STRING57, STRING58, STRING59, STRING60, STRING61, STRING62, STRING63, STRING64, STRING65, STRING66, STRING67, STRING68, STRING69, STRING70, STRING71, STRING72, STRING73, STRING74, STRING75, STRING76, STRING77, STRING78, STRING79, STRING80, STRING81, STRING82, STRING83, STRING84, STRING85, STRING86, STRING87, STRING88, STRING89, STRING90, STRING91, STRING92, STRING93, STRING94, STRING95, STRING96, STRING97, STRING98, STRING99, STRING100

# ======[BIO]======


@bot1.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot2.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot3.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot4.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot5.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot6.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot7.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot8.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot9.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot10.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot11.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot12.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot13.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot14.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot15.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot16.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot17.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot18.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot19.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot20.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot21.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot22.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot23.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot24.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot25.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot26.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot27.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot28.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot29.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot30.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot31.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot32.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot33.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot34.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot35.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot36.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot37.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot38.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot39.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot40.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot41.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot42.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot43.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot44.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot45.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot46.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot47.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot48.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot49.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot50.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot51.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot52.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot53.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot54.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot55.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot56.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot57.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot58.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot59.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot60.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot61.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot62.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot63.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot64.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot65.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot66.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot67.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot68.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot69.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot70.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot71.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot72.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot73.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot74.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot75.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot76.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot77.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot78.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot79.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot80.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot81.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot82.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot83.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot84.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot85.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot86.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot87.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot88.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot89.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot90.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot91.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot92.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot93.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot94.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot95.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot96.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot97.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot98.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot99.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))
@bot100.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}bio"))



async def _(e):
    usage = "𝗠𝗼𝗱𝘂𝗹𝗲 𝗡𝗮𝗺𝗲 = 𝗕𝗶𝗼\n\nCommand:\n\n.bio <Message to set Bio of Userbot accounts>"
    if e.sender_id in SMEX_USERS:
        yukki = ("".join(e.text.split(maxsplit=1)[1:])).split(" ", 1)     
        if len(e.text) > 5:
            bio = str(yukki[0])
            text = "`Changing Bio..`"
            event = await eor(e, text, parse_mode=None, link_preview=None )
            try:
                await e.client(functions.account.UpdateProfileRequest(about=bio))
                await event.edit("`Succesfully Changed Bio!`")
            except Exception as e:
                await event.edit(str(e))   
        else:
            await eor(e, usage, parse_mode=None, link_preview=None )
