from Config import HNDLR, BOT_TOKEN, BOT_HNDLR, ALIVE_NAME, ALIVE_LOGO, BOTLOG_CHATID, HASH_CHAT, REPO_LINK, STRING, SUDO, BIO_MESSAGE, API_ID, API_HASH, HEROKU_API_KEY, UPSTREAM_REPO, UPSTREAM_REPO_BRANCH, UPSTREAM_REPO_URL, HEROKU_APP_NAME
from Config import STRING, STRING2, STRING3, STRING4, STRING5, STRING6, STRING7, STRING8, STRING9, STRING10, STRING11, STRING12, STRING13, STRING14, STRING15, STRING16, STRING17, STRING18, STRING19, STRING20, STRING21, STRING22, STRING23, STRING24, STRING25, STRING26, STRING27, STRING28, STRING29, STRING30, STRING31, STRING32, STRING33, STRING34, STRING35, STRING36, STRING37, STRING38, STRING39, STRING40, STRING41, STRING42, STRING43, STRING44, STRING45, STRING46, STRING47, STRING48, STRING49, STRING50, STRING51, STRING52, STRING53, STRING54, STRING55, STRING56, STRING57, STRING58, STRING59, STRING60, STRING61, STRING62, STRING63, STRING64, STRING65, STRING66, STRING67, STRING68, STRING69, STRING70, STRING71, STRING72, STRING73, STRING74, STRING75, STRING76, STRING77, STRING78, STRING79, STRING80, STRING81, STRING82, STRING83, STRING84, STRING85, STRING86, STRING87, STRING88, STRING89, STRING90, STRING91, STRING92, STRING93, STRING94, STRING95, STRING96, STRING97, STRING98, STRING99, STRING100


# ======[PING!]======       


@bot1.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot2.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot3.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot4.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot5.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot6.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot7.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot8.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot9.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot10.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot11.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot12.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot13.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot14.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot15.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot16.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot17.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot18.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot19.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot20.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot21.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot22.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot23.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot24.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot25.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot26.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot27.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot28.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot29.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot30.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot31.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot32.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot33.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot34.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot35.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot36.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot37.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot38.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot39.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot40.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot41.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot42.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot43.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot44.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot45.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot46.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot47.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot48.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot49.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot50.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot51.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot52.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot53.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot54.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot55.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot56.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot57.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot58.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot59.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot60.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot61.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot62.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot63.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot64.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot65.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot66.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot67.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot68.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot69.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot70.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot71.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot72.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot73.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot74.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot75.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot76.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot77.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot78.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot79.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot80.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot81.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot82.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot83.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot84.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot85.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot86.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot87.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot88.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot89.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot90.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot91.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot92.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot93.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot94.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot95.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot96.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot97.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot98.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot99.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@bot100.on(events.NewMessage(outgoing=True, incoming=True, pattern=f"\\{HNDLR}ping$"))
@xbot.on(events.NewMessage(pattern=f"\\{BOT_HNDLR}ping$"))


async def ping(e):
    if e.sender_id in SMEX_USERS:
        start = datetime.now()
        text = "Pong!"
        event = await eor(e, text, parse_mode=None, link_preview=None )
        end = datetime.now()
        ms = (end-start).microseconds / 1000
        await event.edit(f"🤖 𝗣𝗼𝗻𝗴!\n`{ms}` 𝗺𝘀")
